apiVersion: v1
kind: Service
metadata:
  name: "cocalc-kubernetes-server-nfs"
  labels:
    run: "cocalc-kubernetes-server-nfs"
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    run: "cocalc-kubernetes-server"
