#!/usr/bin/env bash

if which sage >/dev/null; then
    sage -python -c "import sys; sys.path.extend(['/cocalc/lib/python2.7/site-packages/']); from smc_sagews.sage_server_command_line import main; main('$1')"
fi
